/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreksRouteImport } from './routes/treks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as MediaRouteImport } from './routes/media'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdvisoriesRouteImport } from './routes/advisories'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DestinationsNewRouteImport } from './routes/destinations.new'
import { Route as DestinationsIdRouteImport } from './routes/destinations.$id'

const TreksRoute = TreksRouteImport.update({
  id: '/treks',
  path: '/treks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisoriesRoute = AdvisoriesRouteImport.update({
  id: '/advisories',
  path: '/advisories',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsNewRoute = DestinationsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DestinationsRoute,
} as any)
const DestinationsIdRoute = DestinationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DestinationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advisories': typeof AdvisoriesRoute
  '/analytics': typeof AnalyticsRoute
  '/bookings': typeof BookingsRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/providers': typeof ProvidersRoute
  '/settings': typeof SettingsRoute
  '/treks': typeof TreksRoute
  '/destinations/$id': typeof DestinationsIdRoute
  '/destinations/new': typeof DestinationsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advisories': typeof AdvisoriesRoute
  '/analytics': typeof AnalyticsRoute
  '/bookings': typeof BookingsRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/providers': typeof ProvidersRoute
  '/settings': typeof SettingsRoute
  '/treks': typeof TreksRoute
  '/destinations/$id': typeof DestinationsIdRoute
  '/destinations/new': typeof DestinationsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advisories': typeof AdvisoriesRoute
  '/analytics': typeof AnalyticsRoute
  '/bookings': typeof BookingsRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/providers': typeof ProvidersRoute
  '/settings': typeof SettingsRoute
  '/treks': typeof TreksRoute
  '/destinations/$id': typeof DestinationsIdRoute
  '/destinations/new': typeof DestinationsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advisories'
    | '/analytics'
    | '/bookings'
    | '/destinations'
    | '/login'
    | '/media'
    | '/providers'
    | '/settings'
    | '/treks'
    | '/destinations/$id'
    | '/destinations/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advisories'
    | '/analytics'
    | '/bookings'
    | '/destinations'
    | '/login'
    | '/media'
    | '/providers'
    | '/settings'
    | '/treks'
    | '/destinations/$id'
    | '/destinations/new'
  id:
    | '__root__'
    | '/'
    | '/advisories'
    | '/analytics'
    | '/bookings'
    | '/destinations'
    | '/login'
    | '/media'
    | '/providers'
    | '/settings'
    | '/treks'
    | '/destinations/$id'
    | '/destinations/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvisoriesRoute: typeof AdvisoriesRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BookingsRoute: typeof BookingsRoute
  DestinationsRoute: typeof DestinationsRouteWithChildren
  LoginRoute: typeof LoginRoute
  MediaRoute: typeof MediaRoute
  ProvidersRoute: typeof ProvidersRoute
  SettingsRoute: typeof SettingsRoute
  TreksRoute: typeof TreksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/treks': {
      id: '/treks'
      path: '/treks'
      fullPath: '/treks'
      preLoaderRoute: typeof TreksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisories': {
      id: '/advisories'
      path: '/advisories'
      fullPath: '/advisories'
      preLoaderRoute: typeof AdvisoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/new': {
      id: '/destinations/new'
      path: '/new'
      fullPath: '/destinations/new'
      preLoaderRoute: typeof DestinationsNewRouteImport
      parentRoute: typeof DestinationsRoute
    }
    '/destinations/$id': {
      id: '/destinations/$id'
      path: '/$id'
      fullPath: '/destinations/$id'
      preLoaderRoute: typeof DestinationsIdRouteImport
      parentRoute: typeof DestinationsRoute
    }
  }
}

interface DestinationsRouteChildren {
  DestinationsIdRoute: typeof DestinationsIdRoute
  DestinationsNewRoute: typeof DestinationsNewRoute
}

const DestinationsRouteChildren: DestinationsRouteChildren = {
  DestinationsIdRoute: DestinationsIdRoute,
  DestinationsNewRoute: DestinationsNewRoute,
}

const DestinationsRouteWithChildren = DestinationsRoute._addFileChildren(
  DestinationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvisoriesRoute: AdvisoriesRoute,
  AnalyticsRoute: AnalyticsRoute,
  BookingsRoute: BookingsRoute,
  DestinationsRoute: DestinationsRouteWithChildren,
  LoginRoute: LoginRoute,
  MediaRoute: MediaRoute,
  ProvidersRoute: ProvidersRoute,
  SettingsRoute: SettingsRoute,
  TreksRoute: TreksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
